/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ModelAnalysisRouteImport } from './routes/model-analysis'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesVehicleIdRouteImport } from './routes/vehicles_.$vehicleId'
import { Route as ListingsListingIdRouteImport } from './routes/listings_.$listingId'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents_.$documentId'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelAnalysisRoute = ModelAnalysisRouteImport.update({
  id: '/model-analysis',
  path: '/model-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesVehicleIdRoute = VehiclesVehicleIdRouteImport.update({
  id: '/vehicles_/$vehicleId',
  path: '/vehicles/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsListingIdRoute = ListingsListingIdRouteImport.update({
  id: '/listings_/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents_/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/documents': typeof DocumentsRoute
  '/listings': typeof ListingsRoute
  '/model-analysis': typeof ModelAnalysisRoute
  '/search': typeof SearchRoute
  '/vehicles': typeof VehiclesRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/documents': typeof DocumentsRoute
  '/listings': typeof ListingsRoute
  '/model-analysis': typeof ModelAnalysisRoute
  '/search': typeof SearchRoute
  '/vehicles': typeof VehiclesRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/documents': typeof DocumentsRoute
  '/listings': typeof ListingsRoute
  '/model-analysis': typeof ModelAnalysisRoute
  '/search': typeof SearchRoute
  '/vehicles': typeof VehiclesRoute
  '/documents_/$documentId': typeof DocumentsDocumentIdRoute
  '/listings_/$listingId': typeof ListingsListingIdRoute
  '/vehicles_/$vehicleId': typeof VehiclesVehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/documents'
    | '/listings'
    | '/model-analysis'
    | '/search'
    | '/vehicles'
    | '/documents/$documentId'
    | '/listings/$listingId'
    | '/vehicles/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/documents'
    | '/listings'
    | '/model-analysis'
    | '/search'
    | '/vehicles'
    | '/documents/$documentId'
    | '/listings/$listingId'
    | '/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/documents'
    | '/listings'
    | '/model-analysis'
    | '/search'
    | '/vehicles'
    | '/documents_/$documentId'
    | '/listings_/$listingId'
    | '/vehicles_/$vehicleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  DocumentsRoute: typeof DocumentsRoute
  ListingsRoute: typeof ListingsRoute
  ModelAnalysisRoute: typeof ModelAnalysisRoute
  SearchRoute: typeof SearchRoute
  VehiclesRoute: typeof VehiclesRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  ListingsListingIdRoute: typeof ListingsListingIdRoute
  VehiclesVehicleIdRoute: typeof VehiclesVehicleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-analysis': {
      id: '/model-analysis'
      path: '/model-analysis'
      fullPath: '/model-analysis'
      preLoaderRoute: typeof ModelAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles_/$vehicleId': {
      id: '/vehicles_/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof VehiclesVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings_/$listingId': {
      id: '/listings_/$listingId'
      path: '/listings/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof ListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents_/$documentId': {
      id: '/documents_/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  DocumentsRoute: DocumentsRoute,
  ListingsRoute: ListingsRoute,
  ModelAnalysisRoute: ModelAnalysisRoute,
  SearchRoute: SearchRoute,
  VehiclesRoute: VehiclesRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  ListingsListingIdRoute: ListingsListingIdRoute,
  VehiclesVehicleIdRoute: VehiclesVehicleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
